# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import c as module_0


def test_case_0():
    bool_0 = False
    with pytest.raises(ZeroDivisionError):
        module_0.divide(bool_0, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    bool_0 = True
    module_0.divide(none_type_0, bool_0)
